### ISSUE TITLE
Jakie IDE byku?

### ISSUE THREAD

**Issue by PerzotProgrammer** [MiloszMichalak/Java#1]
#### Chciałbym się jej nauczyć!

**Comment by MiloszMichalak** [comment]
Siema gosciu, ja uzywam ja intelliJ ultimate bo jestem dobrym programmerem

**Comment by PerzotProgrammer** [comment]
A jaka wersja JDK?

**Comment by MiloszMichalak** [comment]
wersja 21, pozdrawiam goraco

**Comment by PerzotProgrammer** [comment]
![icegif-1095](https://github.com/MiloszMichalak/Java/assets/114557740/f16e4181-65fb-4f0b-8233-a8eadcc4c455)
